name: Discord PR Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # Replace with your actual Discord role ID
          ROLE_ID=${{ secrets.DISCORD_ROLE_ID }}
          
          # Truncate PR body if too long
          TRUNCATED_BODY=$(echo "$PR_BODY" | head -c 500)
          if [ ${#PR_BODY} -gt 500 ]; then
            TRUNCATED_BODY="${TRUNCATED_BODY}..."
          fi
          
          # Create Discord message with role mention
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"content\": \"<@&${ROLE_ID}>\",
                 \"embeds\": [{
                   \"title\": \"$PR_TITLE #$PR_NUMBER\",
                   \"url\": \"$PR_URL\",
                   \"color\": 5814783,
                   \"fields\": [
                     {
                       \"name\": \"Author\",
                       \"value\": \"$PR_AUTHOR\",
                       \"inline\": true
                     },
                     {
                       \"name\": \"Description\",
                       \"value\": \"${TRUNCATED_BODY:-No description provided}\"
                     }
                   ]
                 }]
               }" \
               "$DISCORD_WEBHOOK_URL"
